---
platform: linux

image_resource:
  type: docker-image
  source: {repository: gradle, tag: 4.9.0-jdk8-alpine}

inputs:
- name: cloudwatch-lambda

run:
  user: root
  path: sh
  dir: cloudwatch-lambda
  args:
    - -exc
    - |
      gradle --stacktrace test buildZip