---
platform: linux

image_resource:
  type: docker-image
  source: {repository: gradle, tag: 4.9.0-jdk8-alpine}

inputs:
- name: cloudwatch-lambda

outputs:
- name: dist

run:
  user: root
  path: sh
  args: [./cloudwatch-lambda/ci/build.sh]