---
resources:
- name: cloudwatch-lambda
  type: git
  source:
    uri: https://github.com/TeliaSoneraNorge/cloudwatch-subscriptions-s3-writer.git

jobs:                          
- name: compile-and-test
  public: true
  aggregate: 
  - get: cloudwatch-lambda
    trigger: true
  plan:
  - task: build
    file: cloudwatch-lambda/ci/build.yml
  - task: deploy
    file: cloudwatch-lambda/ci/awsdeploy.yml
    params:
      AWS_ACCESS_KEY_ID:  ((telia-common-logs-prod-access-key))
      AWS_SECRET_ACCESS_KEY:  ((telia-common-logs-prod-secret-key))
      AWS_SESSION_TOKEN:  ((telia-common-logs-prod-session-token))
      AWS_DEFAULT_REGION:  eu-west-1