---
resources:
- name: cloudwatch-lambda
  type: git
  source:
    uri: https://github.com/TeliaSoneraNorge/cloudwatch-subscriptions-s3-writer.git

jobs:                          
- name: compile-and-test
  public: true
  plan:
  - get: cloudwatch-lambda
    trigger: true
  - task: build
    file: cloudwatch-lambda/ci/build.yml
  - task: deploy
    file: cloudwatch-lambda/ci/deploy.yml
      AWS_DEFAULT_REGION:  eu-west-1